## 2.3. 线性代数

### 2.3.1标量
**标量（scalar）**：标量是指只有大小、没有方向的物理量1。

它是物理学中与“矢量”相对的概念，矢量既有大小又有方向，而标量仅由数值和单位即可完全确定


In [39]:
import torch
#实例化两个标量
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x + y, x * y, x.shape,y.shape

(tensor(5.), tensor(6.), torch.Size([]), torch.Size([]))

### 2.3.2. 向量
向量可以被视为标量值组成的列表。 这些标量值被称为向量的元素（element）或分量（component）。 当向量表示数据集中的样本时，它们的值具有一定的现实意义。 例如，如果我们正在训练一个模型来预测贷款违约风险，可能会将每个申请人与一个向量相关联， 其分量与其收入、工作年限、过往违约次数和其他因素相对应。 在数学表示法中，向量通常记为粗体、小写的符号 ($x$,$y$,$z$)

大量文献认为列向量是向量的默认方向，在本书中也是如此。 在数学中，向量
可以写为：
\begin{split}\mathbf{x} =\begin{bmatrix}x_{1}  \\x_{2}  \\ \vdots  \\x_{n}\end{bmatrix},\end{split}

In [40]:
x = torch.arange(4)
x#x是一维张量也就是向量

tensor([0, 1, 2, 3])

In [41]:
x[3]

tensor(3)

向量的长度通常称为向量的维度（dimension）。

与普通的Python数组一样，我们可以通过调用Python的内置len()函数来访问张量的长度。

In [42]:
len(x)#内置函数len()

4

**维度的两种含义**
1. 张量的维度（张量的阶数）：

- 指张量有多少个轴
- 也称为张量的阶数或秩
- 例如：
    - 标量：0维张量（没有轴）
    - 向量：1维张量（1个轴）
    - 矩阵：2维张量（2个轴）
    - 3维数组：3维张量（3个轴）

2. 轴的维度（轴的长度）：

- 指某个轴上有多少个元素
- 即该轴的"大小"或"长度"
- 通过 .shape 属性查看

In [43]:
x.shape#访问对象 x 的属性 shape

torch.Size([4])

正如向量将标量从零阶推广到一阶，矩阵将向量从一阶推广到二阶。 矩阵，我们通常用粗体、大写字母来表示 （例如，$X$,$Y$,$Z$）， 在代码中表示为具有两个轴的张量。

数学表示法使用来表示矩阵

\begin{split}\mathbf{A}=\begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \\ \end{bmatrix}.\end{split}

当调用函数来实例化张量时， 我们可以通过指定两个分量和来创建一个形状为的矩阵。

In [44]:
A = torch.arange(20).reshape(5, 4)#5行4列矩阵
print(A)
A[1:2,0:1]

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])


tensor([[4]])

In [45]:
A.T#矩阵A的转置

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

### 2.3.4. 张量
就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建具有更多轴的数据结构。 张量（本小节中的“张量”指代数对象）是描述具有任意数量轴的
维数组的通用方法。 例如，向量是一阶张量，矩阵是二阶张量。 张量用特殊字体的大写字母表示<math xmlns="http://www.w3.org/1998/Math/MathML" data-semantic-complexity="1">
  <mrow data-mjx-texclass="ORD" data-semantic-complexity="1">
    <mi mathvariant="sans-serif" data-semantic-type="identifier" data-semantic-role="latinletter" data-semantic-font="sans-serif" data-semantic-annotation="clearspeak:simple" data-semantic-id="0" data-semantic-complexity="1">X</mi>
  </mrow>
</math>， 它们的索引机制与矩阵类似。

当我们开始处理图像时，张量将变得更加重要，图像以n维数组形式出现， 其中3个轴对应于高度、宽度，以及一个通道（channel）轴， 用于表示颜色通道（红色、绿色和蓝色）。 现在先将高阶张量暂放一边，而是专注学习其基础知识。

In [46]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

### 2.3.5. 张量算法的基本性质
标量、向量、矩阵和任意数量轴的张量（本小节中的“张量”指代数对象）有一些实用的属性。 

按元素运算保持形状不变

两个矩阵的按元素乘法称为Hadamard积（哈达玛积）**注意不是矩阵的乘法，这个是对应元素相乘**（数学符号<math xmlns="http://www.w3.org/1998/Math/MathML" data-semantic-complexity="1">
  <mo data-semantic-type="operator" data-semantic-role="multiplication" data-semantic-id="0" data-semantic-complexity="1">&#x2299;</mo>
</math>）
\begin{split}\mathbf{A} \odot \mathbf{B} =
\begin{bmatrix}
    a_{11}  b_{11} & a_{12}  b_{12} & \dots  & a_{1n}  b_{1n} \\
    a_{21}  b_{21} & a_{22}  b_{22} & \dots  & a_{2n}  b_{2n} \\
    \vdots & \vdots & \ddots & \vdots \\
    a_{m1}  b_{m1} & a_{m2}  b_{m2} & \dots  & a_{mn}  b_{mn}
\end{bmatrix}.\end{split}


In [47]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘。

In [48]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

### 2.3.6. 降维
我们可以对任意张量进行的一个有用的操作是计算其元素的和。 数学表示法使用$\sum$符号表示求和。 为了表示长度为d的向量中元素的总和，可以记为$\sum_{i=1}^dx_i$
。 在代码中可以调用计算求和的函数：

In [49]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

默认情况下，调用求和函数会沿所有的轴降低张量的维度，使它变为一个标量。 我们还可以指定张量沿哪一个轴来通过求和降低维度。 

以矩阵为例，为了通过**求和所有行的元素来降维（轴0）**，可以在调用函数时指定axis=0。 由于输入矩阵沿0轴降维以生成输出向量，因此输入轴0的维数在输出形状中消失。
(**指定axis=1将通过汇总所有列的元素降维（轴1）**)

In [50]:
A_sum_axis0 = A.sum(axis=1)
A_sum_axis0, A_sum_axis0.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

一个与求和相关的量是平均值（mean或average）。 我们通过将总和除以元素总数来计算平均值。 在代码中，我们可以调用函数来计算任意形状张量的平均值。

In [51]:
A.mean(), A.sum() / A.numel()
#是 PyTorch 中用于计算张量中元素总个数的函数。

(tensor(9.5000), tensor(9.5000))

#### 2.3.6.1. 非降维求和
但是，有时在调用函数来计算总和或均值时保持轴数不变会很有用。

In [52]:
sum_A = A.sum(axis = 1,keepdims = True)
print(sum_A)
sum_A.shape

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])


torch.Size([5, 1])

例如，由于sum_A在对每行进行求和后仍保持两个轴，我们可以通过广播将A除以sum_A。

- 广播机制原理
当两个张量形状不同时，PyTorch会自动扩展较小的张量以匹配较大的张量形状，然后进行逐元素运算。

In [53]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

如果我们想沿某个轴计算A元素的累积总和， 比如axis=0（按行计算），可以调用cumsum函数。 此函数不会沿任何轴降低输入张量的维度。

In [54]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

### 2.3.7. 点积（Dot Product）
我们已经学习了按元素操作、求和及平均值。另一个最基本的操作之一是点积（也称为数量积、内积）。给定两个向量$\mathbf{x}, \mathbf{y} \in \mathbb{R}^d$，它们的点积（dot product）$\mathbf{x}^\top \mathbf{y}$（或$\langle \mathbf{x}, \mathbf{y} \rangle$）是相同位置的按元素乘积的和：$\mathbf{x}^\top \mathbf{y} = \sum_{i=1}^{d} x_i y_i$。

在PyTorch中，点积会返回一个标量（0维张量）

In [55]:
y = torch.ones(4, dtype = torch.float32)
z=torch.dot(x, y)
x, y, z,z.shape

(tensor([0., 1., 2., 3.]),
 tensor([1., 1., 1., 1.]),
 tensor(6.),
 torch.Size([]))

注意，我们可以通过执行按元素乘法(哈达玛乘法)，然后进行求和来表示两个向量的点积：

In [56]:
torch.sum(x*y)

tensor(6.)

### 2.3.8. 矩阵-向量积

现在我们知道如何计算点积，可以开始理解**矩阵-向量积（matrix-vector product）**。回顾分别在 (2.3.2) 和 (2.3.1) 中定义的矩阵$\mathbf{A} \in \mathbb{R}^{m \times n}$和向量$\mathbf{x} \in \mathbb{R}^n$。让我们将矩阵$\mathbf{A}$用它的行向量表示：
$$
\mathbf{A} = \begin{bmatrix}
\mathbf{a}_1^\top \\
\mathbf{a}_2^\top \\
\vdots \\
\mathbf{a}_m^\top
\end{bmatrix}, \tag{2.3.5}
$$
其中每个$\mathbf{a}_i^\top \in \mathbb{R}^n$都是行向量，表示矩阵的第$i$行。矩阵向量积$\mathbf{A}\mathbf{x}$是一个长度为$m$的列向量，其第$i$个元素是点积$\mathbf{a}_i^\top \mathbf{x}$：
$$
\mathbf{A}\mathbf{x} = \begin{bmatrix}
\mathbf{a}_1^\top \\
\mathbf{a}_2^\top \\
\vdots \\
\mathbf{a}_m^\top
\end{bmatrix} \mathbf{x} = \begin{bmatrix}
\mathbf{a}_1^\top \mathbf{x} \\
\mathbf{a}_2^\top \mathbf{x} \\
\vdots \\
\mathbf{a}_m^\top \mathbf{x}
\end{bmatrix}. \tag{2.3.6}
$$

我们可以把一个矩阵$\mathbf{A} \in \mathbb{R}^{m \times n}$乘法看作一个从$\mathbb{R}^n$到$\mathbb{R}^m$向量的转换。这些转换是非常有用的，例如可以用方阵的乘法来表示旋转。后续章节将讲到，我们也可以使用矩阵-向量积来描述在给定前一层的值时，求解神经网络每一层所需的复杂计算。

---

### 💡 核心概念拆解
1.  **矩阵-向量积的本质**
    矩阵和向量相乘，本质上就是**矩阵的每一行与向量做点积**。
    - 矩阵$\mathbf{A}$是$m$行$n$列，向量$\mathbf{x}$是$n$维列向量，结果是一个$m$维列向量。
    - 结果的第$i$个元素，就是矩阵第$i$行和向量$\mathbf{x}$的点积。

2.  **直观理解：线性变换**
    矩阵乘法可以看作一种“函数”，把一个$n$维空间里的向量，线性变换到$m$维空间里。
    - 比如用方阵（$m=n$）乘以向量，可以实现旋转、缩放、投影等几何变换。
    - 在神经网络中，每一层的线性计算本质上就是矩阵-向量积，把上一层的特征向量，变换成本层的输出向量。

3.  **与点积的关系**
    你之前学的点积，是矩阵-向量积的“最小单元”。矩阵的每一行和向量的点积，共同构成了最终的结果向量。


**在代码中使用张量表示矩阵-向量积，我们使用mv函数**。 当我们为矩阵A和向量x调用torch.mv(A, x)时，会执行矩阵-向量积。 

注意，A的列数（沿轴1的长度）必须与x的行数（其长度）相同。

In [57]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

### 2.3.9 矩阵乘法
矩阵乘法的函数是mm函数

|函数|	特点	|适用场景
| --- | --- | --- |
|torch.matmul	| 自动广播，支持高维 |	通用矩阵乘法 |
torch.mm	| 仅支持2D矩阵	| 简单矩阵乘法
torch.bmm	| 仅支持3D批处理矩阵	| 批处理矩阵乘法

In [58]:
B = torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

### 2.3.10范数
事实上，欧几里得距离是一个$L_2$范数：假设$n$维向量$\mathbf{x}$中的元素是$x_1, \dots, x_n$，其$L_2$范数是向量元素平方和的平方根：
$$
\|\mathbf{x}\|_2 = \sqrt{\sum_{i=1}^n x_i^2} \tag{2.3.14}
$$
其中，在$L_2$范数中常常省略下标2，也就是说$\|\mathbf{x}\|$等同于$\|\mathbf{x}\|_2$。在代码中，我们可以按如下方式计算向量的$L_2$范数。


In [62]:
u = torch.tensor([3.0,-4.])
u,torch.norm(u)# torch.norm(u) 默认情况下计算的是 L2 范数

(tensor([ 3., -4.]), tensor(5.))

深度学习中更经常地使用$L_2$范数的平方，也会经常遇到$L_1$范数，它表示为向量元素的绝对值之和：
$$
\|\mathbf{x}\|_1 = \sum_{i=1}^n |x_i|. \tag{2.3.15}
$$
与$L_2$范数相比，$L_1$范数受异常值的影响较小。 为了计算$L_1$范数，我们将绝对值函数和按元素求和组合起来。



In [63]:
torch.abs(u).sum()

tensor(7.)

### 2.3.13练习

- 对于任意形状的张量 X，len(X) 总是对应于张量第一个轴（axis=0）的长度。而X.shape则是返回完整的张量维度信息

In [ ]:
test = torch.arange(24).reshape(2,3,4)
len(test),test.shape

(2, torch.Size([2, 3, 4]))

In [69]:
test.sum(axis = 0),test.sum(axis = 1),test.sum(axis = 2)

(tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 tensor([[ 6, 22, 38],
         [54, 70, 86]]))


对于形状为(2,3,4)的张量test，在不同轴上求和的结果形状如下：

1. test.sum(axis=0)：
- 沿轴0（第一个维度）求和
- 原始形状(2,3,4)中，轴0的长度为2
- 求和后，该维度被压缩，新形状为(3,4)

2. test.sum(axis=1)：
- 沿轴1（第二个维度）求和
- 原始形状(2,3,4)中，轴1的长度为3
- 求和后，该维度被压缩，新形状为(2,4)

3. test.sum(axis=2)：
- 沿轴2（第三个维度）求和
- 原始形状(2,3,4)中，轴2的长度为4
- 求和后，该维度被压缩，新形状为(2,3)